# .github/workflows/biome.yml
name: 'Biome'

# Event for the workflow
on: push

# List of jobs
jobs:
  biome:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: 22
            cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run Biome
        run: npm run biome:check